version: '3.3'
services:
  gojapan-db:
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    container_name: gojapan_db
#    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
        - ./db:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: gojapan
        MYSQL_DATABASE: gojapan
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin123
        MYSQL_USER_1: front
        MYSQL_PASSWORD_1: admin123
    ports:
        - 23306:3306
    networks:
        app_net:
          ipv4_address: 172.30.0.4
  # api:
  #   build:
  #     dockerfile: docker/api/Dockerfile
  #     context: .
  #   container_name: cuoi_api
  #   ports:
  #     - 1234:80
  #   networks:
  #     app_net:
  #       ipv4_address: 172.30.0.3
  #   environment:
  #     APP_NAME: API
  #     APP_ENV: local
  #     APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
  #     APP_DEBUG: "true"
  #     APP_URL: http://localhost:1234

  #     LOG_CHANNEL: stack

  #     DB_CONNECTION: mysql
  #     DB_HOST: 172.30.0.4
  #     DB_PORT: 3306
  #     DB_DATABASE: cass
  #     DB_USERNAME: cass_admin
  #     DB_PASSWORD: cass_admin123

  #     BROADCAST_DRIVER: log
  #     CACHE_DRIVER: file
  #     QUEUE_CONNECTION: sync
  #     SESSION_DRIVER: file
  #     SESSION_LIFETIME: 120

  #     REDIS_HOST: 127.0.0.1
  #     REDIS_PASSWORD: null
  #     REDIS_PORT: 6379

  #     MAIL_DRIVER: smtp
  #     MAIL_HOST: smtp.mailtrap.io
  #     MAIL_PORT: 2525
  #     MAIL_USERNAME: null
  #     MAIL_PASSWORD: null
  #     MAIL_ENCRYPTION: null

  #     APP_MAINTENANCE: "false"
  #   volumes:
  #     - ./cuoiass-api:/var/www/laravel
  #     - ./cuoiass-api/storage/logs:/var/www/storage/logs

  go-japan-admin:
    build:
      dockerfile: docker/admin/Dockerfile
      context: .
    container_name: gojapan_admin
    ports:
      - 1235:80
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    environment:
      APP_NAME: ADMIN
      APP_ENV: local
      APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
      APP_DEBUG: "true"
      APP_URL: http://localhost:1235
      API_URL: api
      LOG_CHANNEL: stack

      DB_CONNECTION: mysql
      DB_HOST: 172.30.0.4
      DB_PORT: 3306
      DB_DATABASE: gojapan
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

    volumes:
      - ./web-admin:/var/www/web-admin
      - ./web-admin/storage/logs:/var/www/storage/logs

  go-japan-front:
    build:
      dockerfile: docker/front/Dockerfile
      context: .
    container_name: gojapan_front
    ports:
      - 1236:80
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    environment:
      APP_NAME: CUSTOMER
      APP_ENV: local
      APP_KEY: base64:5IDClfWg31l/n0lcabxDu2RzVOi2TuzbV4otITTCwtg=
      APP_DEBUG: "true"
      APP_URL: http://localhost:1236
      API_URL: api
      LOG_CHANNEL: stack

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

    volumes:
      - ./web-front:/var/www/web-front
      - ./web-front/storage/logs:/var/www/storage/logs

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
#         gateway: 172.30.0.1
